-- Basic
require('core.plugins')
require('core.mappings')
require('core.colors')
require('core.configs')
require('core.commands')


-- Plugins
require("plugins.neotree")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.mason")
require("plugins.telescope")
require("plugins.cmp")
require("plugins.nullls")
require("plugins.autopairs")
require("plugins.buffline")
require("plugins.comments")
require("plugins.dashboard")
require("plugins.gitsigns")
require("plugins.lualine")
require("plugins.toggleterm")
require("plugins.blame")
require("plugins.bookmarks")
require("plugins.scrollbar")
require("plugins.hlslens")
require("plugins.tokyonight")
require("plugins.codecompanion")

